added few more which were failing during the build
go get github.com/labstack/echo/v4
Error: #10 0.179 main.go:8:2: no required module provides package github.com/labstack/echo/v4/middleware; to add it:
#10 0.179 	go get github.com/labstack/echo/v4/middleware
Error: #10 0.179 main.go:9:2: no required module provides package github.com/thanhpk/randstr; to add it:
#10 0.179 	go get github.com/thanhpk/randstr